### ISSUE TITLE
SQL injection risk

### ISSUE THREAD

**Issue by tch1bo** [PadamSethia/shorty#3]
Hello,

I noticed that in function app.py:reroute() the variable short_url is used to build an SQL query without prior sanitization (lines 138-146). This can lead to an SQL injection.  

An easy way to fix it would be using prepared statements as everywhere else in file app.py.

**Comment by highoncarbs** [comment]
Thanks a lot ! Will check into it and push a fix . Also if you'd be willing to do a PR for the fix that'd be awesome.
